Path: bgeserver.de!not-for-mail
From: =?iso-8859-1?Q?Ren=E9_K=F6cher?= <shirk@bitspin.org>
Newsgroups: bgepartei.de.test
Subject: Footer-Test
Date: Sat, 3 Apr 2010 00:18:31 +0200
Organization: BGEpartei Deutschland - Testbetrieb
Lines: 6
Sender: shirkrin@news.bgeserver.de
Message-ID: <hp5qfn$8fh$1@bgeserver.de>
Mime-Version: 1.0
Control: cancel
Content-Type: text/plain; charset=iso-8859-1; format=flowed
Content-Transfer-Encoding: 8bit
X-Complaints-To: usenet@news.bgeserver.de
NNTP-Posting-Date: Fri, 2 Apr 2010 22:18:34 +0000 (UTC)
User-Agent: Unison/2.0.5
Xref: bgeserver.de bgepartei.de.test:941

Mit oder ohne Umbrüche??

-- 
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments

