Delivered-To: test@synfu.suite
Return-Path: <test-bounces@lists.bgeserver.de>
X-Spam-Flag: NO
X-Spam-Score: -1.318
X-Spam-Status: No, score=-1.318 required=2.5 tests=[AWL=-0.938,
	BAYES_00=-2.599, TVD_SPACE_RATIO=2.219]
Message-ID: <4BA66070.6090901@synuf.suite>
Date: Sun, 21 Mar 2010 19:07:44 +0100
From: SynFU Testsuite <test@synfu.suite>
MIME-Version: 1.0
To: "test@lists.bgeserver.de" <test@lists.bgeserver.de>
X-Enigmail-Version: 1.0.1
Subject: [Test] Test Header [ignore]
X-BeenThere: test@lists.bgeserver.de
X-Mailman-Version: 2.1.11
Precedence: list
List-Id: =?utf-8?q?Testliste_f=C3=BCr_Tests_der_Synchronisation_mit_Syncom?=
	<test.lists.bgeserver.de>
List-Unsubscribe: <https://service.bgeserver.de/mailman/options/test>,
	<mailto:test-request@lists.bgeserver.de?subject=unsubscribe>
List-Archive: <https://service.bgeserver.de/pipermail/test>
List-Post: <mailto:test@lists.bgeserver.de>
List-Help: <mailto:test-request@lists.bgeserver.de?subject=help>
List-Subscribe: <https://service.bgeserver.de/mailman/listinfo/test>,
	<mailto:test-request@lists.bgeserver.de?subject=subscribe>
Sender: test-bounces@lists.bgeserver.de
Errors-To: test-bounces@lists.bgeserver.de

Test ignored headers filter.

